apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.web.service.name }}-db-volume"
spec:
  storageClassName: hostpath
  capacity:
    storage: {{ .Values.db.volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp