---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Chart.Name }}-role-namespaced
rules:
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [{{ .Values.crd.apiGroup }}]
    resources: [pods, persistentvolumeclaims, persistentvolume, services]
    verbs: [create, list, watch, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Chart.Name }}-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-role-namespaced
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
