apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pythonapps.anirudh.io
  namespace: pythonapp
spec:
  scope: Namespaced
  group: anirudh.io
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["db_size"]
              properties:
                db_size:
                  type: string
      served: true
      storage: true
  names:
    kind: PythonApp
    plural: pythonapps
    singular: pythonapp
